export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const FETCH_MEDICINE = "FETCH_MEDICINE";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const DELETE_MEDICINE = "DELETE_MEDICINE";
export const UPDATE_MEDICINE = "UPDATE_MEDICINE";
export const LOADING_MED = "LOADING_MED";
export const ERROR_MED = "ERROR_MED";

export const FETCH_PATIENT = "FETCH_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const LOADING_PATIENT = "LOADING_PATIENT";
export const ERROR_PATIENT = "ERROR_PATIENT";
